---
title: 'MUSA 5080 Midterm: Predictive model for home prices in Charlotte, NC'
author: "Zhanchao Yang"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: journal
    highlight: tango
    toc: true
    code_folding: hide
    code_download: yes
    toc_float:
      collapsed: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(caret)
library(ggcorrplot)
library(sf)
library(tidycensus)
```


# Introduction

# Data Collection & Exploring

## Load and Clean the Data

```{r, results='hide'}
house<- st_read("data/studentData.geojson")
```
```{r}
summary(house)
```
```{r}
house<- house %>%
  select(price, bedrooms,yearbuilt,fullbaths, halfbaths, shape_Area, totalac, heatedarea, storyheigh, numfirepla, bldggrade,units)  %>%
  filter(!is.na(price) & !is.na(bedrooms) & !is.na(yearbuilt) & !is.na(fullbaths) & !is.na(halfbaths) & !is.na(shape_Area) & !is.na(totalac) & !is.na(heatedarea) & !is.na(storyheigh) & !is.na(numfirepla) & !is.na(bldggrade) & !is.na(units))
```

# Model Building & Evaluation

# Spatial Analysis & Residual Diagnostics

# Conclusion
